"""
Quick setup script to configure test phone numbers and emails

This creates/updates the .env file with your test configuration.
"""

import os
from pathlib import Path

def setup_test_config():
    """Interactive setup for test configuration"""
    print("="*70)
    print("🔧 TEST CONFIGURATION SETUP")
    print("="*70)
    print("\nThis will configure your test phone numbers and emails.")
    print("Phone numbers must be in E.164 format (e.g., +919876543210)\n")
    
    # Get inputs
    family_phone = input("Enter YOUR phone number (for family notifications): ").strip()
    family_email = input("Enter YOUR email (for family notifications): ").strip()
    hospital_phone = input("Enter TEAMMATE's phone number (for hospital/dispatcher): ").strip()
    hospital_email = input("Enter TEAMMATE's email (for pre-auth token): ").strip()
    
    # Validate phone numbers (basic check)
    if family_phone and not family_phone.startswith("+"):
        print(f"⚠️  Warning: Phone number should start with + (e.g., +919876543210)")
        family_phone = "+" + family_phone.lstrip("+")
    
    if hospital_phone and not hospital_phone.startswith("+"):
        print(f"⚠️  Warning: Phone number should start with + (e.g., +919876543210)")
        hospital_phone = "+" + hospital_phone.lstrip("+")
    
    # Create .env file
    env_file = Path(".env")
    env_content = f"""# Trauma Detection System - Test Configuration
# Generated by setup_test_env.py

# Test Phone Numbers and Emails
FAMILY_PHONE={family_phone}
FAMILY_EMAIL={family_email}
HOSPITAL_PHONE={hospital_phone}
HOSPITAL_EMAIL={hospital_email}

# Emergency Services
EMERGENCY_DISPATCHER_NUMBER=108

# Optional: API Keys (leave empty for mock mode)
GOOGLE_MAPS_API_KEY=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=
SENDGRID_API_KEY=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
"""
    
    # Write to .env file
    with open(env_file, "w") as f:
        f.write(env_content)
    
    print(f"\n✅ Configuration saved to {env_file}")
    print("\n📋 Summary:")
    print(f"  Family Phone: {family_phone}")
    print(f"  Family Email: {family_email}")
    print(f"  Hospital Phone: {hospital_phone}")
    print(f"  Hospital Email: {hospital_email}")
    print("\n🚀 Next steps:")
    print("  1. Start the server: python app.py")
    print("  2. Run the test: python test_crash.py")
    print("="*70)


if __name__ == "__main__":
    setup_test_config()

